---
- name: Ensure `/etc/docker` directory exists.
  file: path=/etc/docker state=directory

- name: Setting Docker daemon configuration.
  set_fact:
    docker_config: "{{ docker_config|combine({ item.key: item.value }) }}"
  when: item.value != ""
  with_dict: "{{ docker_options }}"

- name: Adding Docker daemon configuraion file on server.
  copy: content="{{ docker_config | to_nice_json }}\n" dest=/etc/docker/daemon.json
  when: docker_config != {}
  notify: restart docker

- name: Adding logrotate configuration for docker containers.
  template:
    src: etc-logrotate.d-docker.j2
    dest: /etc/logrotate.d/docker
    owner: root
    group: root
    mode: "0644"
  when: docker_enable_logrotate

- name: Adding logrotate configuration for docker containers.
  template:
    src: etc-logrotate.d-docker_volumes.j2
    dest: /etc/logrotate.d/docker_volumes
    owner: root
    group: root
    mode: "0644"
  when: docker_enable_volumes_logrotate
