---
- name: Ensure `/etc/docker` directory exists.
  file: path=/etc/docker state=directory

- name: Setting Docker daemon configuration.
  set_fact:
    docker_config: "{{ docker_config|combine({ item.key: item.value }) }}"
  when: item.value != ""
  with_dict: "{{ docker_options }}"

- name: Adding Docker daemon configuraion file on server.
  copy: content="{{ docker_config | to_nice_json }}\n" dest=/etc/docker/daemon.json
  when: docker_config != {}
  notify: restart docker
